### PR TITLE
Improve size section layout according to design

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/webstudio-is/webstudio-designer/issues/759

Spacing a little not clear so wrapped with common grid

Screenshot 2023-01-10 at 16 55 40

## Code Review

- [ ] hi @rpominov , I need you to do
  - detailed review (read every line)

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `designer/env-check.js` if mandatory

### CODE REVIEW

**Comment by taylornowotny** [comment]
The defaults are not correct. Please use the default values from the design.
Min Width & Min Height have a default of 0px.
Width & Height have a default of Auto. (Do not show the computed value, show "Auto").

Default values on a new box in prod:
Screenshot 2023-01-10 at 8 47 54 AM

Design:
Screenshot 2023-01-10 at 8 49 40 AM

**Comment by TrySound** [comment]
Changed title. This is only layout.

Though it's not clear how we implement keywords support. auto and non are no the only supported keywords. Are we not gonna show dropdown button?
image

**Comment by taylornowotny** [comment]
> Changed title. This is only layout.
> 
> Though it's not clear how we implement keywords support. auto and non are no the only supported keywords. Are we not gonna show dropdown button? image

Ok, the layout looks great!

We will consider the keywords question. But for now yes, do not show a dropdown menu only the unit menu.

**Comment by TrySound** [comment]
Btw this is not true if we follow css. Initial value is auto. 0 behaves a little differently

> Min Width & Min Height have a default of 0px.

https://developer.mozilla.org/en-US/docs/Web/CSS/min-width#formal_definition

**Comment by kof** [comment]
> Btw this is not true if we follow css. Initial value is auto. 0 behaves a little differently

webflow doesn't actually set min- values to 0 but shows 0 in the UI, its actually wrong, @taylornowotny do you know any practical implication there?

**Comment by kof** [comment]
E.g. for max-width wf shows correct: 'none', it seems to me we should stay with correct browser values

**Comment by taylornowotny** [comment]
> Btw. there is another problem with min-width/min-height or actually a solution related to it - in nested flex layouts we use min-width: 0; to ensure the box respects layout, its a hack as far as I know but it seems to be the best solution that exists and we started adding it to all components in our own design system.
> 
> https://makandracards.com/makandra/66994-css-flex-and-min-width
> 
> So if we don't have any other solution, we should just set min-width in our presetStyle for all elements.

Sounds like this is the reason for min width & min height to have a default value of 0.

**Comment by kof** [comment]
> Sounds like this is the reason for min width & min height to have a default value of 0.

I checked, even though webflow shows in the UI 0, they don't apply it as a preset. So webflow is kinda wrong twice, I am not sure why they do it.

**Comment by taylornowotny** [comment]
Are we in agreement to use 0 for min-width & min-height default value for the flexbox reason?

I am not aware of any reason to do it any particular way. 0 is the same as "None" so I have no preference there. I have never had or heard any complaints about Webflow's size section.

**Review by rpominov — APPROVED** [review]

**Pull request merged**
