### PR TITLE
Get rid from remix scripts in published site

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/webstudio-is/webstudio-designer/issues/238

Remix is app level. App should not leak into reusable packages. Here scripts were burried somewhere deep and affected unexpected part of the app.

Here moved out of react-sdk only remix scripts. Ideally move out everything else as well.

## Before requesting a review

- [ ] if the PR is WIP - use draft mode
- [x] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")
- [ ] what kind of review is needed?
  - [x] conceptual
  - [ ] detailed
  - [x] with testing

## Test cases

- [ ] step by step interaction description and what is expected to happen

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `designer/env-check.js` if mandatory

### CODE REVIEW

**Comment by kof** [comment]
Hmm, Remix is app level in the designer, but if sdk is rendering using Remix, it is also part of the published site. A full name for that react sdk is actually remix-react-sdk (should probably rename)

It seems like you are moving things from one place into another, but in the end, in both cases, the same would end up rendered on the canvas. What do I miss?

**Comment by rpominov** [comment]
Might be a good idea to make `react-sdk` framework agnostic actually, so people could do something similar to https://github.com/webstudio-is/webstudio-landing but not use Remix. 

Or maybe someone has a big project where a different framework is used and they want to use Webstudio to build just a couple of pages...

Not sure this should be a priority right now though, as it will make things harder like: https://github.com/webstudio-is/webstudio-designer/pull/488

**Comment by TrySound** [comment]
> Might be a good idea to make react-sdk framework agnostic actually

Yep, this is my intention. Remix does nothing useful in sdk. Only mess with component responsibility.

**Comment by TrySound** [comment]
> but in the end, in both cases, the same would end up rendered on the canvas. What do I miss?

You miss published site which does not need any of this

**Comment by kof** [comment]
Not sure why you say this, published site also needs scripts and scroll restoration

**Comment by kof** [comment]
As discussed, we are rendering a remix app in the worker and will soon be able to build a new worker per project, so we don't need to turn it into a static site.

**Pull request closed without merging**
