### PR TITLE
Sync zoom and modify with shared shortcuts

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/webstudio-is/webstudio-designer/issues/1002

Synchronizing shortcuts with pubsub is complicated because we need to configure each case. Here instead I synchronized zoom store and run shortcuts on both designer and canvas. This way whole logic tied to state instead of event.

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `designer/env-check.js` if mandatory

### CODE REVIEW

**Review by kof — COMMENTED** [review]
Works, can we please also add "ctrl +-"? I just realized that this one prevents typing but allows zooming, so one can zoom while being in the focused input, otherwise one has to unfocus first.

cmd+ is already used for browse-level zoom and we don't want to break this complete layout zoom feature

**Comment by TrySound** [comment]
ctrl won't work for windows users, maybe alt?

**Comment by kof** [comment]
alt/option is fine as well, why is control not working? system one like cmd++?

**Comment by TrySound** [comment]
Yes, "windows" keyboards don't have command. ctrl is used instead for same use cases.

**Comment by TrySound** [comment]
Hm, with alt looks like there is an issue too. It types character.

**Comment by TrySound** [comment]
ok, let it be control. We can address this when windows users give feedback.

**Comment by kof** [comment]
> ok, let it be control. We can address this when windows users give feedback.

Actually using control is same problem as using cmd on mac - it overrides native zoom behavior, so people can't actually increase font size of the interface, which is very bad, we had this shortcut before and switched to just +- without modifiers

**Comment by kof** [comment]
I am assuming ctrl++- is the windows zoom shortcut for native browser zoom, isn't it?

**Comment by TrySound** [comment]
Yep. Figma solve this by overriding browser zoom

**Comment by kof** [comment]
Discussed in the chat, both of 2 worlds:
1. keep native shortcut
2. support shift+modifier so that it works in inputs
3. support +- without modifiers in non-inputs

**Comment by TrySound** [comment]
It's done

**Review by kof — APPROVED** [review]

**Pull request merged**
