### PR TITLE
fix vercel deployments

### PR DESCRIPTION
**Pull request by LonJonn**
Fixes deployments for Vercel by making sure all required dependencies are available in the serverless environment.

For this to work, we have to instruct yarn not to hoist dependences for the `designer` package. That way the @vercel/remix builder will successfully crawl and include the node_modules folder within the app directory using @vercel/nft.

This "nohoist" configuration is necessary since Prisma is used. Prisma generates its own runtime during `npx prisma generate` (found in `node_modules/.prisma/client/libquery_engine-PLATFORM-openssl-X.X.X.node`) which is platform-specific and must be done during Vercel's build pipeline to download the correct binary. In order for Prisma to download the binary in the correct location, "@prisma/client" must be installed in `app/designer/node_modules`.

I've also updated Remix and its associated packages. Updating @remix/dev removes the need for loading environment variables with `dotenv` during development.

Finally, the Vercel project settings need additional configuration to make sure the Prisma client is generated during deployment. Below are the necessary config values.

image

### CODE REVIEW

**Review by okonet — APPROVED** [review]
🥳

**Comment by okonet** [comment]
It's working! Yay!!! 🎉

**Comment by okonet** [comment]
Thanks so much for your help!!!

**Comment by okonet** [comment]
Not sure why but after merging this into our branch I’m getting this on Vercel:

Build Failed
File /vercel/path0/apps/designer/api/index.js does not exist.

Any ideas? I

**Comment by LonJonn** [comment]
Ah I forgot to configure turborepo to include the built `api/index.js` file. Update the `pipeline.build.outputs` field in turbo.json to be:
```
"outputs": ["dist/**", "build/**", "api/**", "public/build/**"]
```

**Comment by okonet** [comment]
Thanks! I'll try it out and let you know.

**Comment by okonet** [comment]
It worked! Thanks so much!

**Pull request merged**
