### PR TITLE
Scrub fixes

### LINKED ISSUE #626: Scrub can stuck when moved over right edge of browser window
1. Scrub any CSS input (e.g. width)
2. Move cursor all the way to the left border of the browser window
3. Move slowly over the border
4. Cursor gets stuck at the border and you can no longer move it

https://github.com/webstudio-is/webstudio-designer/blob/984e8902ac3a8d708071af57c519aad0e90611af/packages/design-system/src/components/primitives/numeric-gesture-control.ts#L125

The if condition fails when `offset` is `0`

### PR DESCRIPTION
**Pull request by rpominov**
- Fixed #626
- Limited movement of cursor to just one coordinate. Not sure it's a good idea, but currently in `main` we move both coordinates for "horizontal" but only one for "vertical", so I've made it consistent.

## Before requesting a review

- [ ] if the PR is WIP - use draft mode
- [x] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")
- [ ] what kind of review is needed?
  - [x] conceptual
  - [ ] detailed
  - [ ] with testing

## Test cases

- [ ] step by step interaction description and what is expected to happen

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `designer/env-check.js` if mandatory

### CODE REVIEW

**Review by kof — CHANGES_REQUESTED** [review]
it doesn't get stuck any more, which is nice!
but now you broke the vertical movement, which is necessary to avoid covering the input at small manipulations, cursor should keep moving freely

**Comment by kof** [comment]
Btw since it was not clear why we need to allow vertical movement, please add a good inline comment, so that we don't attempt to delete it again

**Comment by rpominov** [comment]
Should we allow free movement in both vertical and horizontal mode? 

Same reason applies for vertical: in the spacing UI cursor can obscure the value when you change e.g. `paddingTop`.

**Comment by kof** [comment]
> Should we allow free movement in both vertical and horizontal mode?

Yes! Movement is free, values change only depending on one direction. So in horizontal mode, my vertical movement doesn't change the value, but I can move freely in any mode.

**Comment by rpominov** [comment]
Got it. Fixed.

**Comment by kof** [comment]
Now it seems that you broke infinite scrub - try to go out of the window, it won't come back on the other side for me.

**Comment by kof** [comment]
Lets add testing scenarios inline in that module, so that everyone touching it knows what to test
1. 2d movement
2. ininite scrub
3. focus behavior
4. selection behavior

**Comment by rpominov** [comment]
I think it's better to document intent of the code rather that writing testing instructions in code comments.

> 2d movement

Already wrote comment

> ininite scrub

Will write

> 3. focus behavior
> 4. selection behavior

These two are in a different module (CssValueInput), and in different PR. Will add comments there.

**Comment by rpominov** [comment]
Fixed infinite scrub and added comment.

**Review by kof — APPROVED** [review]
its perfect now

**Pull request merged**
