### PR TITLE
Use sources as type deifnitions

### PR DESCRIPTION
**Pull request by TrySound**
Right now our build and CI take a lot of time. 1:40min - 2min on CI and 1min locally. We spend time on vercel, on main CI, on publish and locally.

At the moment in packages anything outside of src folder is not checked because of rootDir.

We have to generate "references" field on precommit.

All these issues can be avoided if remove .d.ts generation completely and specify sources in "types" field. This way we get zero build time for types and can switch to other build tool (like esbuild) for .js generation and get almost instant build on vercel, on main CI and on publish.

Downsides

- it can be slower (actually not really caz we delete .tsbuildinfo cache anyway and we can still generate it with incremental flag)
- it contraditcs recommended practices for published packages (we can generate .d.ts in publish script only and use "types" as source internally)

## Before requesting a review

- [ ] if the PR is WIP - use draft mode
- [x] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")
- [ ] what kind of review is needed?
  - [x] conceptual
  - [ ] detailed
  - [ ] with testing

## Test cases

- [ ] step by step interaction description and what is expected to happen

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `designer/env-check.js` if mandatory

### CODE REVIEW

**Comment by kof** [comment]
I have seen a few more downsides in that article, are you aware of them?

https://moonrepo.dev/docs/guides/javascript/typescript-project-refs#what-about-not-using-project-references-and-only-using-source-files

**Comment by kof** [comment]
To me 2 min is not such a huge problem right now, I am more concerned with the complexity and amount of problems/breaking things and having to sink dev time into understanding some complex scenario that broke.

If I understand correctly the way we have it now is the most straight forward way for typescript as it treats our internal packages same way it treats every other installed package and it's the recommended and supported way from typescript team.

I would personally want to revisit this once we actually have serious perf issues that we need to fix.

**Comment by TrySound** [comment]
Yep, I saw this article

> Loading declaration files are much faster than source files.

Not much, we still delete ts cache and do check of sources in editor

> You'll lose all the benefits of TypeScript's incremental caching and compilation. TypeScript will consistently load, parse, and evaluate these source files every time. This is especially true for CI environments.

Again, we delete cache

> When using package.json workspaces, bundlers and other tools may consider these source files "external" as they're found in node_modules. This will require custom configuration to allow it.

typescript is the only tool using "types", works perfectly

> It breaks consistency. Consistency with the npm ecosystem, and consistency with how packaging and TypeScript was designed to work. If all packages are internal, then great, but if you have some packages that are published, you now have 2 distinct patterns for "using packages" instead of 1.

We can setup .d.ts generation specifially for published package, but doesn't matter until before we go beta, we probably won't expose much to user. Only types and cli may be enough.

**Comment by kof** [comment]
We delete cache only when we call build, this is a bit of a separate story, improving the `build` command performance. We rarely have to call build, most of the time we just use `yarn dev` - this one has to be really fast

**Comment by TrySound** [comment]
With this references option we still consume sources, not .d.ts files. They are not regenerated. And tsserver does not "consistently load, parse, and evaluate these source files every time". It's true only for build.

**Comment by TrySound** [comment]
My indention to make build as fast as dev.

**Review by kof — APPROVED** [review]

**Review by istarkov — APPROVED** [review]
hope it will be better

**Pull request merged**
