### PR TITLE
Check mark in Combo Boxes can be lost or be incorrect in case of input changes

### LINKED ISSUE #610: Check mark in Combo Boxes can be lost or be incorrect in case of input changes
Reproduce:
Set width to auto, and click Enter.
image

Enter "a" into the input.
image

`auto` must have a Check mark as on the previous screenshot, but it doesn't.

Or if we enter `fit-content`
image
It now shows Check mark but should not.

The issue is here 
https://github.com/webstudio-is/webstudio-designer/blob/35af8358e9538b44ed5b7916b04713013ef28aca/packages/design-system/src/components/combobox.tsx#L203

We need to detect "selected" item based on saved value and not on current.

### PR DESCRIPTION
**Pull request by istarkov**
closes #610

## Before requesting a review

- [ ] if the PR is WIP - use draft mode
- [ ] made a self-review
- [x] added inline comments where things may be not obvious (the "why", not "what")
- [ ] what kind of review is needed?
  - [ ] conceptual
  - [ ] detailed
  - [x] with testing

## Test cases

- [ ] step by step interaction description and what is expected to happen

## Before merging

- [x] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `designer/env-check.js` if mandatory

### CODE REVIEW

**Comment by istarkov** [comment]
Probably better to move "currentState" inside `CssValueInput` in that case public API of `CssValueInput` would be a little bit simpler vs current. 
```{
 value,
 onChange,
 onPreview
}```

instead of current 
```
{
 value,
 selectedItem,
 onChange,
 onChangeComplete,
 onPreview
}
```

Now we have that each Component must have 2 value states:
1. Global which we change on Enter or on Blur
2. Intermediate state used for editing which is different from Global as we need to hold additional things like Highlighted items, intermediate value, color input, color Picker value etc...

And It's not good that internal type of components is leaked outside. Probably we don't want the same component to be edited simultaneously as it will need to share all that internal state that's hard.

WDYT?

**Review by rpominov — APPROVED** [review]

**Comment by rpominov** [comment]
> Probably better to move "currentState" inside CssValueInput

Noticed only after approved. Good idea

**Comment by kof** [comment]
We already started standardizing handlers for preview vs final on this language:

onChange - called on each change, can be frequent
onChangeComplete - final change, can't be frequent

So I don't want to add `onPreview` callback and actually we need to make other things that have similar situations use the same semantics

**Comment by kof** [comment]
Having intermediate state outside of the control and passing it to it has an advantage - you can coordinate the logic between multiple controls for intermediate value changes.

E.g. flex has row and column gap controls. Each has a scrub. When scrubbing one in the linked mode, they both should change simultaneously.

Currently its not right.

**Comment by istarkov** [comment]
`onPreview` came from the fact that `highlightedIndex` is controlled inside `Downshift` and we really has no reason to share it between components. On any +- hard components some state will always be "internal"
Otherwise, we need to move up everything - `useFilter` we use inside Combobox (has state),
highlightedIndex - not need to be shared, has state.  
Fixing api surface for internal components will not make life easier.

**Comment by kof** [comment]
We could have 2 values over props: value, intermediateValue. Both can be matched to whatever is used internally

**Comment by istarkov** [comment]
Renamed.

**Pull request merged**
