### PR TITLE
Fix follow up issues from CSF branch

### LINKED ISSUE #151: Layout with value as an input field seems broken
- [ ] Layout with value as an input field seems broken
Screenshot 2022-07-04 at 21 15 56

_Originally posted by @kof in https://github.com/webstudio-is/webstudio-designer/issues/53#issuecomment-1174129080_

### LINKED ISSUE #152: Wrong props don't show as error or something and also don't let me enter value, one of these needs to be enabled I guess?
- [ ] Wrong props don't show as error or something and also don't let me enter value, one of these needs to be enabled I guess?

Screenshot 2022-07-04 at 21 19 08

_Originally posted by @kof in https://github.com/webstudio-is/webstudio-designer/issues/53#issuecomment-1174136273_

### LINKED ISSUE #153: data- properties should always be enabled, right? Maybe except of the once we use in the system? e.g. data-component, data-id and a few more .... though maybe we just need to switch to something like data-webstudio-something to avoid conflicts
- [ ] data- properties should always be enabled, right? Maybe except of the once we use in the system? e.g. data-component, data-id and a few more .... though maybe we just need to switch to something like data-webstudio-something to avoid conflicts

Screenshot 2022-07-04 at 21 20 26

_Originally posted by @kof in https://github.com/webstudio-is/webstudio-designer/issues/53#issuecomment-1174140453_

### PR DESCRIPTION
**Pull request by okonet**
Closes #151
Closes #152
Closes #153

### CODE REVIEW

**Comment by kof** [comment]
Looking much better now, a few more things:

- [ ] visual bugs with the tooltip's design system:

    Screenshot 2022-07-18 at 20 06 10
    Screenshot 2022-07-18 at 20 07 11

**Comment by okonet** [comment]
This is a good follow up IMO which isn't relevant to this Pr. Feel free to create a new issue and I'll take a look.

**Comment by kof** [comment]
Another one: we should focus the input field when clicking + button, making a follow up issue

**Comment by kof** [comment]
And the last one: we need some better logic to identify the properties we show right away, because user may not know what they need and we still need some baseline for each component, e.g. form always needs target etc, I am not sure which logic to apply, we can go as well with a hardcoded list for now for each component, just the important basics

**Pull request merged**
