### PR TITLE
Deprecate legacy icon button in design system

### PR DESCRIPTION
**Pull request by TrySound**
We are implementing new design with different variants so first deprecate old implemention and then step by step migrate to new version.

## Before requesting a review

- [ ] if the PR is WIP - use draft mode
- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")
- [ ] what kind of review is needed?
  - [x] conceptual
  - [ ] detailed
  - [ ] with testing

## Test cases

- [ ] step by step interaction description and what is expected to happen

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `designer/env-check.js` if mandatory

### CODE REVIEW

**Comment by rpominov** [comment]
Didn't realise you're working on this. I have this issue https://github.com/webstudio-is/webstudio-designer/issues/450 , didn't get to it yet, but if you're going to implement the new button component that will be used as both button with text and button with icon, then this is the same issue. Maybe you should take it then.

**Comment by rpominov** [comment]
> It's icon button specifically. They are different in design system afaik.

Yes, but as far as I understand @taylornowotny we going to use `<Button><Icon></Button>` in most of the places where we use `<IconButton>` currently.

Taylor describes this in one of the videos in https://discord.com/channels/955905230107738152/973300187567095858/1049410399604314153

**Comment by rpominov** [comment]
In this video: https://discord.com/channels/955905230107738152/1049410399604314153/1049439800102502530

**Comment by TrySound** [comment]
I guess these are different buttons. Icon button used to change canvas. Button for everything else.

**Comment by rpominov** [comment]
> Icon button used to change canvas.

So you want to implement this one and just want to free up "IconButton" name, so you're adding `_depricated`? But when you implement it, not all cases of `IconButton_depricated` will be replaced with the new one?

Sounds good if so.

**Review by rpominov — APPROVED** [review]

**Comment by taylornowotny** [comment]
Look at the layers and you'll see the two containers. Click on a container to see the gap & padding settings.
Screenshot 2022-12-08 at 8 51 21 AM

**Pull request merged**
